# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Avid Pixels
author: Vashishtha Jogi
email: vashishthajogi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Travel diary of an avid photographer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://avid.photos" # the base hostname & protocol for your site
collections:
    albums:
        output: true
        permalink: /albums/:path/

# Build settings
# Build settings
markdown: kramdown
sass:
  style: compressed
